### ISSUE TITLE
Improve help command

### ISSUE THREAD

**Issue by CharlyCst** [CharlyCst/parrot#9]
**Why**

Currently the help command:
1. is out of date (missing commands).
2. only gives an overview of each commands.

**How**

The help command should accept an optional parameter matching one of the existing commands. Without that parameter, help prints the list of commands as it does today, but if the name of a command is passed then it prints a detailed explanation of that command.

**Tasks**

- [ ] Add missing commands
- [ ] Accept an optional parameter
- [ ] Update the readme
